export async function publishToGitHub(
  token: string,
  repoName: string,
  files: Record<string, string>
): Promise<{ url: string; success: boolean; error?: string }> {
  const headers = {
    Authorization: `token ${token}`,
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
  }

  // Get username
  const userRes = await fetch('https://api.github.com/user', { headers })
  if (!userRes.ok) return { url: '', success: false, error: 'Invalid GitHub token' }
  const user = await userRes.json()
  const username = user.login

  // Create repo
  const createRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: repoName,
      description: 'Generated by AlfaComp AI Builder',
      private: false,
      auto_init: false,
    }),
  })

  if (!createRes.ok && createRes.status !== 422) {
    return { url: '', success: false, error: 'Failed to create repository' }
  }

  // Upload files
  for (const [path, content] of Object.entries(files)) {
    const encoded = btoa(unescape(encodeURIComponent(content)))
    const fileRes = await fetch(
      `https://api.github.com/repos/${username}/${repoName}/contents/${path}`,
      {
        method: 'PUT',
        headers,
        body: JSON.stringify({
          message: `Add ${path}`,
          content: encoded,
        }),
      }
    )
    if (!fileRes.ok) {
      console.warn(`Failed to upload ${path}`)
    }
  }

  return {
    url: `https://github.com/${username}/${repoName}`,
    success: true,
  }
}
